### ISSUE TITLE
[version upgrade request] paperspigot 1.16.5 not work

### ISSUE THREAD

**Issue by CatEricka** [HexoCraft/WorldEditStructureSelector#1]
minecraft version: paperspigot 1.16.5
fawe version: 1.17-419

```log
[18:46:04] [Server thread/INFO]: [WorldEditStructureSelector] Enabling WorldEditStructureSelector v1.1.0*
[18:46:04] [Server thread/WARN]: java.lang.NoSuchFieldException: modifiers
[18:46:04] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.reflection.util.AccessUtil.setAccessible(AccessUtil.java:42)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.configuration.helper.Annotations.load(Annotations.java:90)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.configuration.helper.Annotations.load(Annotations.java:78)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.configuration.Configuration.load(Configuration.java:106)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.configuration.Config.<init>(Config.java:58)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.WssPlugin.onEnable(WssPlugin.java:55)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:965)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.Bukkit.reload(Bukkit.java:726)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:46:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[18:46:04] [Server thread/WARN]: java.lang.NoSuchFieldException: modifiers
[18:46:04] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.reflection.util.AccessUtil.setAccessible(AccessUtil.java:42)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.configuration.helper.Annotations.load(Annotations.java:90)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.configuration.helper.Annotations.load(Annotations.java:78)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.configuration.Configuration.load(Configuration.java:106)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.configuration.Messages.<init>(Messages.java:84)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.WssPlugin.onEnable(WssPlugin.java:56)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:965)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.Bukkit.reload(Bukkit.java:726)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:46:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[18:46:04] [Server thread/WARN]: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='commandMap', types=[]}] in class class org.bukkit.craftbukkit.v1_16_R3.CraftServer
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:175)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:27)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:76)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.reflection.resolver.FieldResolver.resolve(FieldResolver.java:74)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.reflection.util.FieldUtil.getField(FieldUtil.java:42)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.reflection.util.FieldUtil.getField(FieldUtil.java:58)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.command.CommandRegistration.getCommandMap(CommandRegistration.java:86)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.command.CommandRegistration.getKnownCommands(CommandRegistration.java:92)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.command.CommandRegistration.isRegisteredCommand(CommandRegistration.java:80)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.command.CommandRegistration.registerCommand(CommandRegistration.java:40)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.api.plugin.Plugin.registerCommands(Plugin.java:71)
[18:46:04] [Server thread/WARN]: 	at com.github.hexocraft.wss.WssPlugin.onEnable(WssPlugin.java:59)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:965)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.Bukkit.reload(Bukkit.java:726)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[18:46:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[18:46:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:46:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[18:46:04] [Server thread/INFO]: --------------------- WorldEditStructureSelector 1.1.0 ---------------------
[18:46:04] [Server thread/INFO]: WorldEdit Structure Selector is enable ...
[18:46:04] [Server thread/INFO]: Integration with FastAsyncWorldEdit
[18:46:04] [Server thread/INFO]: ----------------------------------------------------------------------------
```

Seems to be a compatibility issue with `com.github.hexocraftapi`

Are there any plans to upgrade to 1.16.5?

**Comment by CatEricka** [comment]
I fork this project and rewrote the code, no longer need external api and compatible with 1.16.5
